name: Fetch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch
        id: fetch
        run: |
          ./ip-blacklist-bjos_cn.sh -n 0 -o raw.txt
          if [ ! -s raw.txt ]; then
            rm -f raw.txt
            exit
          fi
          sort raw.txt | uniq -c | sort -nr | awk '{ print $2 "\t" $1 }' >all-count.txt
          awk '{ print $1 }' all-count.txt | sort -o all.txt
          rm -f raw.txt
          if [ -s all-count.txt ] && [ -s all.txt ]; then
            echo "DATE=$(date -u)" >>"$GITHUB_OUTPUT"
          fi

      - name: Update
        if: ${{ steps.fetch.outputs.DATE != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.fetch.outputs.DATE }}